include("${CMAKE_CURRENT_LIST_DIR}/../SemVer.cmake")

function(expect_valid version expected_core expected_prerelease expected_build)
    vibeplayer_parse_semver("${version}" parsed)
    if(NOT parsed_VALID)
        message(FATAL_ERROR "Expected '${version}' to be valid: ${parsed_ERROR}")
    endif()
    if(NOT parsed_CORE STREQUAL expected_core)
        message(FATAL_ERROR "Unexpected core for '${version}': ${parsed_CORE}")
    endif()
    if(NOT parsed_PRERELEASE STREQUAL expected_prerelease)
        message(FATAL_ERROR "Unexpected prerelease for '${version}': ${parsed_PRERELEASE}")
    endif()
    if(NOT parsed_BUILD_METADATA STREQUAL expected_build)
        message(FATAL_ERROR "Unexpected build metadata for '${version}': ${parsed_BUILD_METADATA}")
    endif()
endfunction()

function(expect_invalid version)
    vibeplayer_parse_semver("${version}" parsed)
    if(parsed_VALID)
        message(FATAL_ERROR "Expected '${version}' to be invalid")
    endif()
endfunction()

expect_valid("1.0.1" "1.0.1" "" "")
expect_valid("1.0.1-alpha" "1.0.1" "alpha" "")
expect_valid("1.0.1-alhpa" "1.0.1" "alhpa" "")
expect_valid("1.0.1-beta.1" "1.0.1" "beta.1" "")
expect_valid("0.0.0-0" "0.0.0" "0" "")
expect_valid("2.4.0-rc.2+build.19" "2.4.0" "rc.2" "build.19")

expect_invalid("1.0")
expect_invalid("v1.0.1")
expect_invalid("01.0.1")
expect_invalid("1.0.1-01")
expect_invalid("1.0.1-")
expect_invalid("1.0.1-alpha..1")
expect_invalid("1.0.1+build_1")
