if(NOT PROJECT_IS_TOP_LEVEL)
    return()
endif()

set(VIBEPLAYER_PACKAGE_VERSION "${PROJECT_VERSION}" CACHE STRING
    "Numeric version embedded in native installer metadata"
)
if(NOT VIBEPLAYER_PACKAGE_VERSION MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
    message(FATAL_ERROR
        "VIBEPLAYER_PACKAGE_VERSION must use the numeric major.minor.patch form"
    )
endif()
string(REPLACE "." ";" VIBEPLAYER_PACKAGE_VERSION_PARTS
    "${VIBEPLAYER_PACKAGE_VERSION}"
)
list(GET VIBEPLAYER_PACKAGE_VERSION_PARTS 0 VIBEPLAYER_PACKAGE_VERSION_MAJOR)
list(GET VIBEPLAYER_PACKAGE_VERSION_PARTS 1 VIBEPLAYER_PACKAGE_VERSION_MINOR)
list(GET VIBEPLAYER_PACKAGE_VERSION_PARTS 2 VIBEPLAYER_PACKAGE_VERSION_PATCH)

set(CPACK_PACKAGE_NAME "vibePlayerQT")
set(CPACK_PACKAGE_VENDOR "gjh303987897")
set(CPACK_PACKAGE_CONTACT
    "gjh303987897 <gjh303987897@users.noreply.github.com>"
)
set(CPACK_PACKAGE_HOMEPAGE_URL
    "https://github.com/gjh303987897/vibeEmbyPlayerQT"
)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Cross-platform Qt Quick media center")
set(CPACK_PACKAGE_VERSION "${VIBEPLAYER_PACKAGE_VERSION}")
set(CPACK_PACKAGE_VERSION_MAJOR "${VIBEPLAYER_PACKAGE_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${VIBEPLAYER_PACKAGE_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${VIBEPLAYER_PACKAGE_VERSION_PATCH}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "vibePlayerQT")
set(CPACK_PACKAGE_EXECUTABLES "vibePlayerQT" "vibePlayerQT")
set(CPACK_CREATE_DESKTOP_LINKS "vibePlayerQT")
set(CPACK_MONOLITHIC_INSTALL ON)
set(CPACK_THREADS 0)
set(CPACK_VERBATIM_VARIABLES ON)

if(WIN32)
    set(CPACK_GENERATOR "NSIS;WIX")

    set(CPACK_NSIS_DISPLAY_NAME "vibePlayerQT")
    set(CPACK_NSIS_PACKAGE_NAME "vibePlayerQT")
    set(CPACK_NSIS_MUI_ICON "${CMAKE_SOURCE_DIR}/icon/app_icon.ico")
    set(CPACK_NSIS_MUI_UNIICON "${CMAKE_SOURCE_DIR}/icon/app_icon.ico")
    set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
    set(CPACK_NSIS_MANIFEST_DPI_AWARE ON)

    set(CPACK_WIX_VERSION 3)
    set(CPACK_WIX_UPGRADE_GUID "471EF922-6CE8-46DE-9F9C-B307F3702E7C")
    set(CPACK_WIX_PRODUCT_ICON "${CMAKE_SOURCE_DIR}/icon/app_icon.ico")
    set(CPACK_WIX_PROGRAM_MENU_FOLDER "vibePlayerQT")
    set(CPACK_WIX_ARCHITECTURE x64)
    set(CPACK_WIX_INSTALL_SCOPE perMachine)
elseif(APPLE)
    set(CPACK_GENERATOR "DragNDrop")
    set(CPACK_DMG_VOLUME_NAME "vibePlayerQT")
    set(CPACK_DMG_FORMAT "UDZO")
else()
    set(CPACK_GENERATOR "DEB;RPM")
    set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")

    set(CPACK_DEBIAN_PACKAGE_NAME "vibeplayerqt")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_CONTACT}")
    set(CPACK_DEBIAN_PACKAGE_SECTION "video")
    set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS_PRIVATE_DIRS
        "usr/${CMAKE_INSTALL_LIBDIR}"
    )
    set(CPACK_DEBIAN_COMPRESSION_TYPE "xz")
    set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")

    set(CPACK_RPM_PACKAGE_NAME "vibeplayerqt")
    set(CPACK_RPM_PACKAGE_GROUP "Applications/Multimedia")
    set(CPACK_RPM_COMPRESSION_TYPE "xz")
    set(CPACK_RPM_FILE_NAME "RPM-DEFAULT")
endif()

include(CPack)
