if(NOT PROJECT_IS_TOP_LEVEL)
    return()
endif()

set(CPACK_PACKAGE_NAME "vibePlayerQT")
set(CPACK_PACKAGE_VENDOR "gjh303987897")
set(CPACK_PACKAGE_CONTACT
    "gjh303987897 <gjh303987897@users.noreply.github.com>"
)
set(CPACK_PACKAGE_HOMEPAGE_URL
    "https://github.com/gjh303987897/vibeEmbyPlayerQT"
)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Cross-platform Qt Quick media center")
set(CPACK_PACKAGE_VERSION "${VIBEPLAYER_SEMVER_FULL}")
set(CPACK_PACKAGE_VERSION_MAJOR "${VIBEPLAYER_SEMVER_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${VIBEPLAYER_SEMVER_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${VIBEPLAYER_SEMVER_PATCH}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "vibePlayerQT")
set(CPACK_PACKAGE_EXECUTABLES "vibePlayerQT" "vibePlayerQT")
set(CPACK_CREATE_DESKTOP_LINKS "vibePlayerQT")
set(CPACK_MONOLITHIC_INSTALL ON)
set(CPACK_THREADS 0)
set(CPACK_VERBATIM_VARIABLES ON)

if(WIN32)
    # MSI product versions only accept a numeric core. Release artifacts retain
    # the complete SemVer supplied by the workflow.
    set(CPACK_PACKAGE_VERSION "${VIBEPLAYER_SEMVER_CORE}")
    set(CPACK_GENERATOR "NSIS;WIX")

    set(CPACK_NSIS_DISPLAY_NAME "vibePlayerQT")
    set(CPACK_NSIS_PACKAGE_NAME "vibePlayerQT")
    set(CPACK_NSIS_MUI_ICON "${CMAKE_SOURCE_DIR}/icon/app_icon.ico")
    set(CPACK_NSIS_MUI_UNIICON "${CMAKE_SOURCE_DIR}/icon/app_icon.ico")
    set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
    set(CPACK_NSIS_MANIFEST_DPI_AWARE ON)

    set(CPACK_WIX_VERSION 3)
    set(CPACK_WIX_UPGRADE_GUID "471EF922-6CE8-46DE-9F9C-B307F3702E7C")
    set(CPACK_WIX_PRODUCT_ICON "${CMAKE_SOURCE_DIR}/icon/app_icon.ico")
    set(CPACK_WIX_PROGRAM_MENU_FOLDER "vibePlayerQT")
    set(CPACK_WIX_ARCHITECTURE x64)
    set(CPACK_WIX_INSTALL_SCOPE perMachine)
elseif(APPLE)
    set(CPACK_GENERATOR "DragNDrop")
    set(CPACK_DMG_VOLUME_NAME "vibePlayerQT")
    set(CPACK_DMG_FORMAT "UDZO")
else()
    set(CPACK_GENERATOR "DEB;RPM")
    set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")

    set(CPACK_DEBIAN_PACKAGE_NAME "vibeplayerqt")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_CONTACT}")
    set(CPACK_DEBIAN_PACKAGE_SECTION "video")
    set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS_PRIVATE_DIRS
        "usr/${CMAKE_INSTALL_LIBDIR}"
    )
    set(CPACK_DEBIAN_COMPRESSION_TYPE "xz")
    set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
    set(CPACK_DEBIAN_PACKAGE_RELEASE "1")

    set(CPACK_RPM_PACKAGE_NAME "vibeplayerqt")
    set(CPACK_RPM_PACKAGE_GROUP "Applications/Multimedia")
    set(CPACK_RPM_COMPRESSION_TYPE "xz")
    set(CPACK_RPM_FILE_NAME "RPM-DEFAULT")

    if(VIBEPLAYER_SEMVER_PRERELEASE)
        set(CPACK_DEBIAN_PACKAGE_VERSION
            "${VIBEPLAYER_SEMVER_CORE}~${VIBEPLAYER_SEMVER_PRERELEASE}"
        )
        string(REPLACE "-" "." VIBEPLAYER_RPM_PRERELEASE
            "${VIBEPLAYER_SEMVER_PRERELEASE}"
        )
        set(CPACK_RPM_PACKAGE_VERSION "${VIBEPLAYER_SEMVER_CORE}")
        set(CPACK_RPM_PACKAGE_RELEASE "0.${VIBEPLAYER_RPM_PRERELEASE}.1")
    else()
        set(CPACK_DEBIAN_PACKAGE_VERSION "${VIBEPLAYER_SEMVER_CORE}")
        set(CPACK_RPM_PACKAGE_VERSION "${VIBEPLAYER_SEMVER_CORE}")
        set(CPACK_RPM_PACKAGE_RELEASE "1")
    endif()
endif()

include(CPack)
