function(vibeplayer_parse_semver version output_prefix)
    set(parse_error "")
    set(version_without_build "${version}")
    set(build_metadata "")

    string(FIND "${version_without_build}" "+" build_separator)
    if(NOT build_separator EQUAL -1)
        math(EXPR build_offset "${build_separator} + 1")
        string(SUBSTRING "${version_without_build}" ${build_offset} -1 build_metadata)
        string(SUBSTRING "${version_without_build}" 0 ${build_separator} version_without_build)
        if(NOT build_metadata MATCHES "^[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*$")
            set(parse_error "build metadata contains an empty or invalid identifier")
        endif()
    endif()

    set(core_version "${version_without_build}")
    set(prerelease "")
    string(FIND "${core_version}" "-" prerelease_separator)
    if(NOT prerelease_separator EQUAL -1)
        math(EXPR prerelease_offset "${prerelease_separator} + 1")
        string(SUBSTRING "${core_version}" ${prerelease_offset} -1 prerelease)
        string(SUBSTRING "${core_version}" 0 ${prerelease_separator} core_version)
        if(NOT prerelease MATCHES "^[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*$")
            set(parse_error "prerelease contains an empty or invalid identifier")
        else()
            string(REPLACE "." ";" prerelease_identifiers "${prerelease}")
            foreach(identifier IN LISTS prerelease_identifiers)
                if(identifier MATCHES "^[0-9]+$" AND identifier MATCHES "^0[0-9]+$")
                    set(parse_error
                        "numeric prerelease identifier '${identifier}' has a leading zero"
                    )
                    break()
                endif()
            endforeach()
        endif()
    endif()

    if(NOT core_version MATCHES
        "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$"
    )
        set(parse_error "the core version must use major.minor.patch without leading zeros")
    else()
        set(version_major "${CMAKE_MATCH_1}")
        set(version_minor "${CMAKE_MATCH_2}")
        set(version_patch "${CMAKE_MATCH_3}")
    endif()

    if(parse_error)
        set(${output_prefix}_VALID FALSE PARENT_SCOPE)
        set(${output_prefix}_ERROR "${parse_error}" PARENT_SCOPE)
        return()
    endif()

    set(${output_prefix}_VALID TRUE PARENT_SCOPE)
    set(${output_prefix}_ERROR "" PARENT_SCOPE)
    set(${output_prefix}_FULL "${version}" PARENT_SCOPE)
    set(${output_prefix}_CORE "${core_version}" PARENT_SCOPE)
    set(${output_prefix}_MAJOR "${version_major}" PARENT_SCOPE)
    set(${output_prefix}_MINOR "${version_minor}" PARENT_SCOPE)
    set(${output_prefix}_PATCH "${version_patch}" PARENT_SCOPE)
    set(${output_prefix}_PRERELEASE "${prerelease}" PARENT_SCOPE)
    set(${output_prefix}_BUILD_METADATA "${build_metadata}" PARENT_SCOPE)
endfunction()
